blank_issues_enabled: false
contact_links:
  - name: Want to Discuss something?
    url: https://www.linkedin.com/company/robotics-sathyabama
    about: For any Discussion, Query.
  - name: Guidelines
    url: https://github.com/Robotics-Club-SIST/robotics-club-sist.github.io/blob/main/CONTRIBUTING.md
    about: Our contribution guidelines (Please go through them).
  - name: Code of Conduct
    url: https://github.com/Robotics-Club-SIST/robotics-club-sist.github.io/blob/main/CODE_OF_CONDUCT.md
    about: Our Code of Conduct (Please go through them).